import marty_verification
import marty_verification_py


def test_production_module_excludes_local_secret_key_operations():
    forbidden = {
        "ed448_generate",
        "ed448_sign",
        "Pkcs12Data",
        "pkcs12_parse",
        "iso9796_scheme1_sign",
        "eac_sign_terminal_challenge",
        "eac_calculate_mac",
        "load_private_key_pem",
        "load_private_key_der",
        "save_private_key_pem",
        "extract_public_key",
        "detect_private_key_type",
        "raw_private_key_to_pkcs8",
        "pkcs8_to_raw_private_key",
        "ed25519_generate",
        "ed25519_sign",
        "x25519_generate",
        "x25519_agree",
        "p256_generate",
        "p256_agree",
        "ecdsa_p256_generate",
        "ecdsa_p384_generate",
        "ecdsa_p521_generate",
        "ecdsa_p256_sign",
        "ecdsa_p384_sign",
        "ecdsa_p521_sign",
        "rsa_generate",
        "rsa_pkcs1_sha256_sign",
        "rsa_pkcs1_sha384_sign",
        "rsa_pkcs1_sha512_sign",
        "rsa_pss_sha256_sign",
        "rsa_pss_sha384_sign",
        "rsa_pss_sha512_sign",
        "generate_key",
        "Jwk",
        "jwk_generate",
        "jws_sign",
        "jws_verify",
        "jwe_encrypt",
        "jwe_decrypt",
        "open_badge_ob2_issue",
        "open_badge_ob3_issue",
        "dtc_sign",
        "CertProfile",
        "CertificateBuilderConfig",
        "build_self_signed_certificate",
        "build_self_signed_certificate_with_key",
        "aes_gcm_encrypt",
        "aes_gcm_decrypt",
        "tdes_cbc_encrypt",
        "tdes_cbc_decrypt",
        "hkdf_sha256",
        "hkdf_sha384",
        "pbkdf2_sha256",
        "generate_random_bytes",
        "NativeBacSession",
        "NativePaceSession",
        "NativeEacChipAuthentication",
        "NativeEacSecureMessaging",
    }

    assert forbidden.isdisjoint(dir(marty_verification))
    assert forbidden.isdisjoint(dir(marty_verification_py))
    for safe_name in (
        "verify_signature",
        "dtc_prepare_signing",
        "dtc_assemble_signature",
        "dtc_verify",
        "open_badge_ob2_verify",
        "open_badge_ob3_verify",
    ):
        assert hasattr(marty_verification, safe_name), safe_name
